import Head from "next/head";
import Link from "next/link";
import { Inter } from "next/font/google";
import { Heading, Text, Box } from "@chakra-ui/react";
// import styles from "@home/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>React TypeScript Examples</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Heading size="lg">Home/Overview</Heading>
        <Box m={2}>
          <Text>
            The purpose of this small application is to demonstrate various uses
            of types in TypeScript inside a React/NEXT application. Each example
            has a functional example along with code snippets that show how
            types are being utilized in that example.
          </Text>
          <Text>
            This application was built with NEXT.js and Chakra UI and is hosted
            on Vercel.
          </Text>
        </Box>
      </main>
    </>
  );
}
